### ISSUE TITLE
Missing li.is-active with pico-file-prefixes

### ISSUE THREAD

**Issue by lollita** [nliautaud/pico-pages-list#11]
Do you can add a class (hasChildActive) to li.has-childs that have childs page li.is-current; to toggle with css selector?

**Comment by nliautaud** [comment]
Hello,
Isn't it already what `.is-active` is indicating ?

**Comment by lollita** [comment]
hello
i have realized that .is-active not display in my output why i have pico-file-prefixes plugin that removes file prefixes.
i have file 123.file.md
$pageID then is  123.file and not file
and
if (strpos($this->current_url, $this->base_url . $childPath) === 0) $class .= ' is-active';
`
not match never.
do it is possible to fix it?

**Comment by nliautaud** [comment]
Thanks for the report.
I'll look into it.

**Comment by lollita** [comment]
I also have found a problem if i not use rewrite rule in line
`
if (strpos(urldecode($this->current_url), $this->base_url . $childPath) === 0) $class .= ' is-active';
`
i have to use:
`
if (strpos(urldecode($this->current_url), $this->base_url . '?'. $childPath) === 0) $class .= ' is-active';
`

**Comment by lollita** [comment]
or i use:
if (strpos(str_replace('/?', '/',urldecode($this->current_url)), $this->base_url . $childPath) === 0) $class .= ' is-active';
`
important also "urldecode".

**Comment by nliautaud** [comment]
There was an issue with this logic when no url_rewriting was used indeed.
I didn't check for `pico-file-prefixes` support yet, it depends on how this plugin handle the stripping.

**Comment by lollita** [comment]
Fix work, ty.
why if I download pico-pages-list-0.3.1.zip I do not have the updates that i have is download PicoPagesList.php raw?

**Comment by nliautaud** [comment]
You're welcome, thanks for the bug report.
I don't know for the zip, maybe some cache issues ?
