### ISSUE TITLE
500 error when installed

### ISSUE THREAD

**Issue by dcrobertson01** [nliautaud/pico-pages-list#20]
Hi - installed on a couple of machines with picoCMS 2.0.4 and get following error:

`
[Thu May  9 20:31:51 2019] PHP Fatal error:  Uncaught RuntimeException: Unable to load plugin 'pico-pages-list' from 'pico-pages-list/pico-pages-list.php': Plugin class not found in /var/lib/nethserver/home/don/htdocs/picocms/pico/vendor/picocms/pico/lib/Pico.php:669
Stack trace:
#0 /var/lib/nethserver/home/don/htdocs/picocms/pico/vendor/picocms/pico/lib/Pico.php(520): Pico->loadLocalPlugins(Array)
#1 /var/lib/nethserver/home/don/htdocs/picocms/pico/vendor/picocms/pico/lib/Pico.php(401): Pico->loadPlugins()
#2 /var/lib/nethserver/home/don/htdocs/picocms/pico/index.php(33): Pico->run()
#3 {main}
  thrown in /var/lib/nethserver/home/don/htdocs/picocms/pico/vendor/picocms/pico/lib/Pico.php on line 669
`

**Comment by matschundbrei** [comment]
Hi,
This might be due to the Issue I layed out in [this pull request](https://github.com/nliautaud/pico-pages-list/pull/19).

Feel free to test my downstream changes do verify this.

Cheers,
J

**Comment by dcrobertson01** [comment]
Hi - is this change in the master repository? I am running PicoCMS using the PHP builtin webserver, but am still getting the error. I've installed PicoCMS using composer, and then used git to install the plugin. But am still getting the error.

**Comment by matschundbrei** [comment]
Hey sorry to hear that. The PR was merged long before your comment, so it seems to be unrelated.

What's somewhat strange to me is the fact that your trace points to 'pico-pages-list/pico-pages-list.php' while the repository contains 'pico-pages-list/PicoPagesList.php'.

Can you try and create a link or rename the file to what the loader expects there.

This seems to be an issue related to your setup. I am running pico behind nginx with php-fpm and I do not get any errors.

Cheers,
J

**Comment by nliautaud** [comment]
Hi !

It seems like you installed the plugin manually by copying the full repo directory.
The plugin should be installed by copying the single php file (see readme), or trough composer.

Don't hesitate to reply, I'll reopen if needed.
